# Website
baseurl:
url: https://cba85.github.io/coolcolors/
title: Cool colors
description: >
  Cool colors in hexadecimal and RGB for your projects.

# Lang
lang: en

# Social
github: https://github.com/cba85/coolcolors

# Legal
author: Clément Barbaza
author_url: https://www.clementbarbaza.com

# Google Analytics
google_analytics: UA-45415607-2

# Build settings
timezone: Europe/Paris
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
